robot:
  type: RobotArm2D
  parameters:
    base_position: [5.0, 5.0]
    link_lengths: [2.1, 2.1]

workspace:
  type: Workspace2D
  parameters:
    limits: [[0, 10.0], [0, 10.0]]

    obstacles:
      # - type: Rectangle
      #   parameters:
      #     xlim: [1.1, 3]
      #     ylim: [5.6, 9.8]
      - type: Polygon
        parameters:
          p_in:
            - [1.1, 5]
            - [3, 6]
            - [3, 9.8]
            - [1.1, 9.8]


      - type: Polygon
        parameters:
          p_in:
            - [1.5, 0.5]
            - [0.5, 1.5]
            - [3, 3.5]
            - [3.6, 2.7]


      - type: Polygon
        parameters:
          p_in:
            - [3.5, 0.7]
            - [4.5, 1.2]
            - [1.5, 3.2]
            - [0.5, 2.7]

      - type: Polygon
        parameters:
          p_in:
            - [5.5, 0.4]
            - [7, 3]
            - [8, 4.7]
            - [9, 3]
            - [8.5, 1.1]

      - type: Polygon
        parameters:
          p_in:
            - [4.1, 7.2]
            - [4.8, 7.4]
            - [4.8, 8.8]
            - [3.7, 9.1]

      # This is equivalent to a Rectangle, just an example to show how other polygons could be defined by their vertices
      - type: Polygon
        parameters:
          p_in:
            - [5, 9]
            - [8, 9]
            - [9, 6]
            - [6.8, 7]
            - [6, 8]

# query -> [[X1, Y1], [X2, Y2]]
queries:
  - [[4, 7], [6, 3]]
  - [[7.5, 5.2], [5, 1]]
  - [[2, 3.9], [6, 6.5]]
  # - [[4, 7], [6, 3]]  
  